### ISSUE TITLE
Deltakerlister

### ISSUE THREAD

**Issue by bhg99** [paulrene/lil#11]
Noen lister er litt kaotiske mtp kontaktinfo... Vet du hva det kan skyldes?

![skjermbilde 2015-04-22 14 00 12](https://cloud.githubusercontent.com/assets/11920969/7273859/ff4014e4-e8f7-11e4-94e0-292da7e86f20.png)

**Comment by paulrene** [comment]
Fikset. Årask: En del variabler som ikke var nullstilt mellom radene i tabellen.
