### ISSUE TITLE
Extra pages under Trim og aktivitet

### ISSUE THREAD

**Issue by bhg99** [paulrene/lil#12]
Lager du en underside på allidrett som heter "allidrett for voksne"? Alternativt to, en som heter "Allidrett for damer" og en som heter "Innebandy for menn"? I tillegg en som heter "Ikke-organisert aktivitet" eller "Ut på tur!"?

**Comment by paulrene** [comment]
Laget 3 nye sider under http://leinstrandil.no/page/trimogaktivitet
